### PR TITLE
Upgrade to tungstenite 0.13.

### PR DESCRIPTION
**Pull request by de-vri-es**
This PR upgrades to `tungstenite` 0.13. It required some changes to error reporting, but nothing major.

This is currently keeping `hyper-tungstenite` on `tungstenite` 0.12, so would be nice to upgrade :)

### CODE REVIEW

**Comment by strohel** [comment]
Hi @de-vri-es, there is currently #147 in the works, which is a superset of this.

If #147 takes longer to finish, it may make sense to merge this one first, but we're actively working on the other one, and most important questions seems to be resolved there.

**Comment by de-vri-es** [comment]
Ah, I see. Well, it's up to the maintainers of course, but it would be nice to get 0.13 support in a release soon :)

**Comment by strohel** [comment]
Okay, #147 has been just merged, superseding this, closing.

@application-developer-DA time for a release?

**Comment by de-vri-es** [comment]
Awesome, thanks!

**Pull request closed without merging**
