### PR TITLE
Use re-exported tungstenite types so its easier to copy examples and …

### PR DESCRIPTION
**Pull request by alexgeek**
…not depend directly on tungstenite.

(I ran into the same confusion as in: https://github.com/snapview/tokio-tungstenite/issues/141)

### CODE REVIEW

**Comment by daniel-abramov** [comment]
Neat :) Would you mind checking the CI errors? It seems like the formatting is a bit off.

**Comment by agalakhov** [comment]
JFYI: we already reexport Tungstenite as a whole:
```
pub use tungstenite;
```

**Comment by alexgeek** [comment]
> JFYI: we already reexport Tungstenite as a whole:
> 
> ```
> pub use tungstenite;
> ```

Should I have done something differently in the PR because of that?

**Comment by agalakhov** [comment]
No, everything looks fine. This only means that there is no need to depend directly of tungstenite even if using non-reexported types.

**Pull request merged**
