### PR TITLE
prepare for native-tls 0.2

### PR DESCRIPTION
**Pull request by mehcode**

### CODE REVIEW

**Comment by application-developer-DA** [comment]
@mehcode thanks for the pull request, did I get it right that we have to wait until the "patch" lands into the release and merge this pull request once `tungstenite-rs` has a new version?

**Comment by mehcode** [comment]
@application-developer-DA Yeah. I just forked and edited trying to upgrade Rust in my own environment (and ultimately failing because of reqwest not yet updating its hyper). 

Once native-tls 0.2 is out we can remove the `[patch]` section of `tungstenite-rs`, release that, and then remove the `[patch]` section here.

**Comment by application-developer-DA** [comment]
Alright.

**Comment by application-developer-DA** [comment]
Implemented within #46

**Pull request closed without merging**
