### PR TITLE
Fix "no-default-features" build failure

### LINKED ISSUE #154: Build with --no-default-features fails
Compilation with `--no-default-features` does not work:
```
$ cargo build --no-default-features
   Compiling tokio-tungstenite v0.13.0
error: unused import: `Request`
  --> src/lib.rs:40:35
   |
40 |         client::{ClientHandshake, Request, Response},
   |                                   ^^^^^^^
   |
note: the lint level is defined here
  --> src/lib.rs:11:52
   |
11 | #![deny(missing_docs, unused_must_use, unused_mut, unused_imports, unused_import_braces)]
   |                                                    ^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `tokio-tungstenite`
```
This happens ever since release 0.10.0, seems as if no one's complaining.

### PR DESCRIPTION
**Pull request by Johannesd3**
Fixes #154.

~It's not ready to merge: The error isn't fixed yet, because I first want to see if the newly added check is effective.~

### CODE REVIEW

**Comment by strohel** [comment]
> The error isn't fixed yet, because I first want to see if the newly added check is effective.

That's a great approach, true TDD. :+1:

**Comment by Johannesd3** [comment]
But the check has failed, that's good, so I will now push a fix (hope it works)

**Review by strohel — APPROVED** [review]
Looks good, thanks.

**Comment by Johannesd3** [comment]
I rebased it to use the formatting fix that was recently added to master.

**Review by jxs — APPROVED** [review]

**Review by application-developer-DA — APPROVED** [review]

**Pull request merged**
